name = "zivebrowser-site"
compatibility_date = "2026-09-07"
compatibility_flags = ["nodejs_compat"]

[vars]
# Public runtime configuration only. Never place secrets in this file.

[[d1_databases]]
binding = "DB"
database_name = "zive-registrations"
database_id = ""d1_databases": [{
    "binding": "DB",
    "database_name": "zive-registrations",
    "database_id": "f7b50993-04e9-4865-b788-e1e789fd2b83"
 }]"
